coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0.5%
        base: auto
        enabled: yes
    patch:
      default:
        target: 90%
        threshold: 10%
        base: auto
        enabled: yes