coverage:
  status:
    project: #add everything under here, more options at https://docs.codecov.com/docs/commit-status
      default:
        # basic
        target: 90%
        threshold: 10%
        base: auto
        enabled: yes
